---
- hosts: servers
  remote_user: root
  tasks:
  - name: install nginx
    apt:
     name: nginx
     state: latest

  - name: start nginx service 
    shell: service nginx start

  - name: install Curl
    apt:
     name: curl
     state: latest

  - name: update curl
    shell: curl -sL https://deb.nodesource.com/setup_7.x | sh

  - name: install Nodejs & npm
    apt:
     name: nodejs
     state: latest

  - name: install git
    apt:
     name: git
     state: latest

  - name: clone repo git
    git:
     repo: https://git.mrzee.fr/student/my-node-project.git
     dest: /var/www/my-node-project 

  - name: install pm2 
    npm:
     name: pm2
     global: yes
     state: latest

  - name: install dependencies project
    npm:
     path: /var/www/my-node-project/myapp

  - name: run myapp
    shell: pm2 start /var/www/my-node-project/myapp/bin/www

  - name: copy vhost folder
    shell: cp /var/www/my-node-project/vhost /etc/nginx/sites-enabled/default

  - name: restart nginx
    shell: service nginx restart 
